<script lang="ts">
	// A recorded rapid-draughts game, AlphaBeta vs AlphaBeta, replayed as a
	// pure-CSS flipbook (no JS): a vertical reel of board frames stepped through
	// one at a time, looping. Frames were generated by the engine at build time.
	import frames from './draughts-frames.json';

	const N = frames.length;
	const seconds = Math.round(N * 0.42);
</script>

<div class="board-term" aria-hidden="true">
	<div class="chrome">
		<span class="dot red"></span>
		<span class="dot amber"></span>
		<span class="dot green"></span>
		<span class="title">rapid-draughts — alphaBeta vs alphaBeta</span>
		<span class="live"></span>
	</div>
	<div class="viewport">
		<div
			class="reel"
			style="animation-duration: {seconds}s; animation-timing-function: steps({N}, end);"
		>
			{#each frames as f (f.n)}
				<div class="frame">
					<div class="meta">
						<span>move {f.n}</span>
						<span class="turn">{f.n % 2 === 0 ? '● dark to move' : '○ light to move'}</span>
					</div>
					<pre class="board">{f.board}</pre>
				</div>
			{/each}
		</div>
	</div>
</div>

<style>
	.board-term {
		--fg: #a9b1d6;
		font-family: var(--font-mono);
		font-size: 0.82rem;
		line-height: 1.5;
		background: #1a1b26;
		color: var(--fg);
		border-radius: 0.6em;
		overflow: hidden;
		margin: var(--spacing-base) 0;
		box-shadow: 0 1.5em 3em -1em rgba(0, 0, 0, 0.35);
	}
	.chrome {
		display: flex;
		align-items: center;
		gap: 0.5em;
		padding: 0.7em 0.9em;
		background: rgba(255, 255, 255, 0.04);
	}
	.dot {
		width: 0.72em;
		height: 0.72em;
		border-radius: 50%;
	}
	.red {
		background: #f7768e;
	}
	.amber {
		background: #e0af68;
	}
	.green {
		background: #9ece6a;
	}
	.title {
		margin-left: 0.4em;
		color: #565f89;
		font-size: 0.88em;
	}
	.live {
		width: 0.5em;
		height: 0.5em;
		border-radius: 50%;
		background: #9ece6a;
		margin-left: auto;
		animation: pulse 1.6s ease-in-out infinite;
	}

	.viewport {
		height: 16.5em;
		overflow: hidden;
	}
	.reel {
		animation-name: reel;
		animation-iteration-count: infinite;
	}
	.frame {
		height: 16.5em;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 0.6em;
	}
	.meta {
		display: flex;
		gap: 1.4em;
		color: #565f89;
		font-size: 0.85em;
	}
	.turn {
		color: #7aa2f7;
	}
	.board {
		margin: 0;
		letter-spacing: 0.14em;
		font-size: 1.15em;
		color: #c0caf5;
	}

	@keyframes reel {
		to {
			transform: translateY(-100%);
		}
	}
	@keyframes pulse {
		0%,
		100% {
			opacity: 1;
		}
		50% {
			opacity: 0.25;
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.reel {
			animation: none;
		}
		.live {
			animation: none;
		}
	}
</style>
